version: '3.8'

services:
  pharmextract:
    build: .
    container_name: pharmextract-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=5000
      # Add your LANGEXTRACT_API_KEY here or use .env file
      - LANGEXTRACT_API_KEY=${LANGEXTRACT_API_KEY}
    volumes:
      # Mount for development - comment out for production
      - ./extraction_results.jsonl:/app/extraction_results.jsonl
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy with nginx for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: pharmextract-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - pharmextract
  #   restart: unless-stopped
